<link rel="stylesheet" href="./app/views/pages/fat-intake-calculator/fat-intake-calculator-style.css">

<section class="container max-w-[991px] mx-auto px-5 md:px-7 coxl:px-10 my-5 lg:my-12">
    <div id="inputdivs" class="accordion grid grid-cols-1 lg:grid-cols-1 gap-5">
        <div class="m-0 cls-shadow h-full bg-white rounded-lg col-span-1">
            <h3 class="text-base xs:text-lg md:text-2xl font-semibold text-start bg-primary_button bg-opacity-90 text-white rounded-lg py-4 lg:py-5 px-4 mb-5">With Live Exchange Rate
            </h3>
            <div class="py-5 px-4">
            <p id="warning" class=" text-primary_button mb-5 ms-2"></p>
                <div class=" grid grid-cols-1 sm:gap-4">
                    <div class="relative flex items-center border rounded-full w-full mb-1 md:mb-8 focus-within:text-primary_button focus-within:border-primary_button maxsm:text-15px">
                        <input type="number" id="amount" step="0.01" min="0" class="w-full h-9 sm:h-10 mx-5 text-xs md:text-sm outline-none" placeholder=" " required>
                        <label for="amount" class="absolute top-[10px] left-[34px] text-label_color duration-300 pointer-events-none">Amount</label>
                    </div>
                </div>
                <div class=" grid md:grid-cols-2 sm:gap-4">
                    <div class="flex m-0 ">
                        <select id="toCurrency" class=" select_class w-full h-9 sm:h-10 outline-none border md:mb-8 maxsm:mt-5 rounded-full sm:m-0 px-2 sm:px-5 text-[#a2adb9] focus:text-primary_button focus:border-primary_button cursor-pointer">

                            <option value="AED">AED: United Arab Emirates Dirham</option>
                            <option value="AFN">AFN: Afghan Afghani</option>
                            <option value="ALL">ALL: Albanian Lek</option>
                            <option value="AMD">AMD: Armenian Dram</option>
                            <option value="ANG">ANG: Netherlands Antillean Guilder</option>
                            <option value="AOA">AOA: Angolan Kwanza</option>
                            <option value="ARS">ARS: Argentine Peso</option>
                            <option value="AUD">AUD: Australian Dollar</option>
                            <option value="AWG">AWG: Aruban Florin</option>
                            <option value="AZN">AZN: Azerbaijani Manat</option>
                            <option value="BAM">BAM: Bosnia-Herzegovina Con. Mark</option>
                            <option value="BBD">BBD: Barbadian Dollar</option>
                            <option value="BDT">BDT: Bangladeshi Taka</option>
                            <option value="BGN">BGN: Bulgarian Lev</option>
                            <option value="BHD">BHD: Bahraini Dinar</option>
                            <option value="BIF">BIF: Burundian Franc</option>
                            <option value="BMD">BMD: Bermudan Dollar</option>
                            <option value="BND">BND: Brunei Dollar</option>
                            <option value="BOB">BOB: Bolivian Boliviano</option>
                            <option value="BRL">BRL: Brazilian Real</option>
                            <option value="BSD">BSD: Bahamian Dollar</option>
                            <option value="BTC">BTC: Bitcoin</option>
                            <option value="BTN">BTN: Bhutanese Ngultrum</option>
                            <option value="BWP">BWP: Botswanan Pula</option>
                            <option value="BYN">BYN: Belarusian Ruble</option>
                            <option value="BZD">BZD: Belize Dollar</option>
                            <option value="CAD">CAD: Canadian Dollar</option>
                            <option value="CDF">CDF: Congolese Franc</option>
                            <option value="CHF">CHF: Swiss Franc</option>
                            <option value="CLF">CLF: Chilean Unit of Account (UF)</option>
                            <option value="CLP">CLP: Chilean Peso</option>
                            <option value="CNH">CNH: Chinese Yuan (Offshore)</option>
                            <option value="CNY">CNY: Chinese Yuan</option>
                            <option value="COP">COP: Colombian Peso</option>
                            <option value="CRC">CRC: Costa Rican Colón</option>
                            <option value="CUC">CUC: Cuban Convertible Peso</option>
                            <option value="CUP">CUP: Cuban Peso</option>
                            <option value="CVE">CVE: Cape Verdean Escudo</option>
                            <option value="CZK">CZK: Czech Republic Koruna</option>
                            <option value="DJF">DJF: Djiboutian Franc</option>
                            <option value="DKK">DKK: Danish Krone</option>
                            <option value="DOP">DOP: Dominican Peso</option>
                            <option value="DZD">DZD: Algerian Dinar</option>
                            <option value="EGP">EGP: Egyptian Pound</option>
                            <option value="ERN">ERN: Eritrean Nakfa</option>
                            <option value="ETB">ETB: Ethiopian Birr</option>
                            <option value="EUR">EUR: Euro</option>
                            <option value="FJD">FJD: Fijian Dollar</option>
                            <option value="FKP">FKP: Falkland Islands Pound</option>
                            <option value="GBP">GBP: British Pound Sterling</option>
                            <option value="GEL">GEL: Georgian Lari</option>
                            <option value="GGP">GGP: Guernsey Pound</option>
                            <option value="GHS">GHS: Ghanaian Cedi</option>
                            <option value="GIP">GIP: Gibraltar Pound</option>
                            <option value="GMD">GMD: Gambian Dalasi</option>
                            <option value="GNF">GNF: Guinean Franc</option>
                            <option value="GTQ">GTQ: Guatemalan Quetzal</option>
                            <option value="GYD">GYD: Guyanaese Dollar</option>
                            <option value="HKD">HKD: Hong Kong Dollar</option>
                            <option value="HNL">HNL: Honduran Lempira</option>
                            <option value="HRK">HRK: Croatian Kuna</option>
                            <option value="HTG">HTG: Haitian Gourde</option>
                            <option value="HUF">HUF: Hungarian Forint</option>
                            <option value="IDR">IDR: Indonesian Rupiah</option>
                            <option value="ILS">ILS: Israeli New Sheqel</option>
                            <option value="IMP">IMP: Manx pound</option>
                            <option value="INR">INR: Indian Rupee</option>
                            <option value="IQD">IQD: Iraqi Dinar</option>
                            <option value="IRR">IRR: Iranian Rial</option>
                            <option value="ISK">ISK: Icelandic Króna</option>
                            <option value="JEP">JEP: Jersey Pound</option>
                            <option value="JMD">JMD: Jamaican Dollar</option>
                            <option value="JOD">JOD: Jordanian Dinar</option>
                            <option value="JPY">JPY: Japanese Yen</option>
                            <option value="KES">KES: Kenyan Shilling</option>
                            <option value="KGS">KGS: Kyrgystani Som</option>
                            <option value="KHR">KHR: Cambodian Riel</option>
                            <option value="KMF">KMF: Comorian Franc</option>
                            <option value="KPW">KPW: North Korean Won</option>
                            <option value="KRW">KRW: South Korean Won</option>
                            <option value="KWD">KWD: Kuwaiti Dinar</option>
                            <option value="KYD">KYD: Cayman Islands Dollar</option>
                            <option value="KZT">KZT: Kazakhstani Tenge</option>
                            <option value="LAK">LAK: Laotian Kip</option>
                            <option value="LBP">LBP: Lebanese Pound</option>
                            <option value="LKR">LKR: Sri Lankan Rupee</option>
                            <option value="LRD">LRD: Liberian Dollar</option>
                            <option value="LSL">LSL: Lesotho Loti</option>
                            <option value="LYD">LYD: Libyan Dinar</option>
                            <option value="MAD">MAD: Moroccan Dirham</option>
                            <option value="MDL">MDL: Moldovan Leu</option>
                            <option value="MGA">MGA: Malagasy Ariary</option>
                            <option value="MKD">MKD: Macedonian Denar</option>
                            <option value="MMK">MMK: Myanma Kyat</option>
                            <option value="MNT">MNT: Mongolian Tugrik</option>
                            <option value="MOP">MOP: Macanese Pataca</option>
                            <option value="MRU">MRU: Mauritanian Ouguiya</option>
                            <option value="MUR">MUR: Mauritian Rupee</option>
                            <option value="MVR">MVR: Maldivian Rufiyaa</option>
                            <option value="MWK">MWK: Malawian Kwacha</option>
                            <option value="MXN">MXN: Mexican Peso</option>
                            <option value="MYR">MYR: Malaysian Ringgit</option>
                            <option value="MZN">MZN: Mozambican Metical</option>
                            <option value="NAD">NAD: Namibian Dollar</option>
                            <option value="NGN">NGN: Nigerian Naira</option>
                            <option value="NIO">NIO: Nicaraguan Córdoba</option>
                            <option value="NOK">NOK: Norwegian Krone</option>
                            <option value="NPR">NPR: Nepalese Rupee</option>
                            <option value="NZD">NZD: New Zealand Dollar</option>
                            <option value="OMR">OMR: Omani Rial</option>
                            <option value="PAB">PAB: Panamanian Balboa</option>
                            <option value="PEN">PEN: Peruvian Nuevo Sol</option>
                            <option value="PGK">PGK: Papua New Guinean Kina</option>
                            <option value="PHP">PHP: Philippine Peso</option>
                            <option value="PKR">PKR: Pakistani Rupee</option>
                            <option value="PLN">PLN: Polish Zloty</option>
                            <option value="PYG">PYG: Paraguayan Guarani</option>
                            <option value="QAR">QAR: Qatari Rial</option>
                            <option value="RON">RON: Romanian Leu</option>
                            <option value="RSD">RSD: Serbian Dinar</option>
                            <option value="RUB">RUB: Russian Ruble</option>
                            <option value="RWF">RWF: Rwandan Franc</option>
                            <option value="SAR">SAR: Saudi Riyal</option>
                            <option value="SBD">SBD: Solomon Islands Dollar</option>
                            <option value="SCR">SCR: Seychellois Rupee</option>
                            <option value="SDG">SDG: Sudanese Pound</option>
                            <option value="SEK">SEK: Swedish Krona</option>
                            <option value="SGD">SGD: Singapore Dollar</option>
                            <option value="SHP">SHP: Saint Helena Pound</option>
                            <option value="SLL">SLL: Sierra Leonean Leone</option>
                            <option value="SOS">SOS: Somali Shilling</option>
                            <option value="SRD">SRD: Surinamese Dollar</option>
                            <option value="SSP">SSP: South Sudanese Pound</option>
                            <option value="STD">STD: São Tomé and Príncipe Dobra (pre-2018)</option>
                            <option value="STN">STN: São Tomé and Príncipe Dobra</option>
                            <option value="SVC">SVC: Salvadoran Colón</option>
                            <option value="SYP">SYP: Syrian Pound</option>
                            <option value="SZL">SZL: Swazi Lilangeni</option>
                            <option value="THB">THB: Thai Baht</option>
                            <option value="TJS">TJS: Tajikistani Somoni</option>
                            <option value="TMT">TMT: Turkmenistani Manat</option>
                            <option value="TND">TND: Tunisian Dinar</option>
                            <option value="TOP">TOP: Tongan Pa anga</option>
                            <option value="TRY">TRY: Turkish Lira</option>
                            <option value="TTD">TTD: Trinidad and Tobago Dollar</option>
                            <option value="TWD">TWD: New Taiwan Dollar</option>
                            <option value="TZS">TZS: Tanzanian Shilling</option>
                            <option value="UAH">UAH: Ukrainian Hryvnia</option>
                            <option value="UGX">UGX: Ugandan Shilling</option>
                            <option value="USD">USD: United States Dollar</option>
                            <option value="UYU">UYU: Uruguayan Peso</option>
                            <option value="UZS">UZS: Uzbekistan Som</option>
                            <option value="VEF">VEF: Venezuelan Bolívar Fuerte (Old)</option>
                            <option value="VES">VES: Venezuelan Bolívar Soberano</option>
                            <option value="VND">VND: Vietnamese Dong</option>
                            <option value="VUV">VUV: Vanuatu Vatu</option>
                            <option value="WST">WST: Samoan Tala</option>
                            <option value="XAF">XAF: CFA Franc BEAC</option>
                            <option value="XAG">XAG: Silver Ounce</option>
                            <option value="XAU">XAU: Gold Ounce</option>
                            <option value="XCD">XCD: East Caribbean Dollar</option>
                            <option value="XDR">XDR: Special Drawing Rights</option>
                            <option value="XOF">XOF: CFA Franc BCEAO</option>
                            <option value="XPD">XPD: Palladium Ounce</option>
                            <option value="XPF">XPF: CFP Franc</option>
                            <option value="XPT">XPT: Platinum Ounce</option>
                            <option value="YER">YER: Yemeni Rial</option>
                            <option value="ZAR">ZAR: South African Rand</option>
                            <option value="ZMW">ZMW: Zambian Kwacha</option>
                            <option value="ZWL">ZWL: Zimbabwean Dollar</option>
                        </select>
                    </div>
                    <div class="flex">
                        <select id="fromCurrency" class=" select_class w-full h-9 sm:h-10 outline-none border rounded-full maxsm:mt-5 sm:m-0 px-2 sm:px-5 text-[#a2adb9] focus:text-primary_button focus:border-primary_button cursor-pointer">

                            <option value="AED">AED: United Arab Emirates Dirham</option>
                            <option value="AFN">AFN: Afghan Afghani</option>
                            <option value="ALL">ALL: Albanian Lek</option>
                            <option value="AMD">AMD: Armenian Dram</option>
                            <option value="ANG">ANG: Netherlands Antillean Guilder</option>
                            <option value="AOA">AOA: Angolan Kwanza</option>
                            <option value="ARS">ARS: Argentine Peso</option>
                            <option value="AUD">AUD: Australian Dollar</option>
                            <option value="AWG">AWG: Aruban Florin</option>
                            <option value="AZN">AZN: Azerbaijani Manat</option>
                            <option value="BAM">BAM: Bosnia-Herzegovina Con. Mark</option>
                            <option value="BBD">BBD: Barbadian Dollar</option>
                            <option value="BDT">BDT: Bangladeshi Taka</option>
                            <option value="BGN">BGN: Bulgarian Lev</option>
                            <option value="BHD">BHD: Bahraini Dinar</option>
                            <option value="BIF">BIF: Burundian Franc</option>
                            <option value="BMD">BMD: Bermudan Dollar</option>
                            <option value="BND">BND: Brunei Dollar</option>
                            <option value="BOB">BOB: Bolivian Boliviano</option>
                            <option value="BRL">BRL: Brazilian Real</option>
                            <option value="BSD">BSD: Bahamian Dollar</option>
                            <option value="BTC">BTC: Bitcoin</option>
                            <option value="BTN">BTN: Bhutanese Ngultrum</option>
                            <option value="BWP">BWP: Botswanan Pula</option>
                            <option value="BYN">BYN: Belarusian Ruble</option>
                            <option value="BZD">BZD: Belize Dollar</option>
                            <option value="CAD">CAD: Canadian Dollar</option>
                            <option value="CDF">CDF: Congolese Franc</option>
                            <option value="CHF">CHF: Swiss Franc</option>
                            <option value="CLF">CLF: Chilean Unit of Account (UF)</option>
                            <option value="CLP" selected>CLP: Chilean Peso </option>
                            <option value="CNH">CNH: Chinese Yuan (Offshore)</option>
                            <option value="CNY">CNY: Chinese Yuan</option>
                            <option value="COP">COP: Colombian Peso</option>
                            <option value="CRC">CRC: Costa Rican Colón</option>
                            <option value="CUC">CUC: Cuban Convertible Peso</option>
                            <option value="CUP">CUP: Cuban Peso</option>
                            <option value="CVE">CVE: Cape Verdean Escudo</option>
                            <option value="CZK">CZK: Czech Republic Koruna</option>
                            <option value="DJF">DJF: Djiboutian Franc</option>
                            <option value="DKK">DKK: Danish Krone</option>
                            <option value="DOP">DOP: Dominican Peso</option>
                            <option value="DZD">DZD: Algerian Dinar</option>
                            <option value="EGP">EGP: Egyptian Pound</option>
                            <option value="ERN">ERN: Eritrean Nakfa</option>
                            <option value="ETB">ETB: Ethiopian Birr</option>
                            <option value="EUR">EUR: Euro</option>
                            <option value="FJD">FJD: Fijian Dollar</option>
                            <option value="FKP">FKP: Falkland Islands Pound</option>
                            <option value="GBP">GBP: British Pound Sterling</option>
                            <option value="GEL">GEL: Georgian Lari</option>
                            <option value="GGP">GGP: Guernsey Pound</option>
                            <option value="GHS">GHS: Ghanaian Cedi</option>
                            <option value="GIP">GIP: Gibraltar Pound</option>
                            <option value="GMD">GMD: Gambian Dalasi</option>
                            <option value="GNF">GNF: Guinean Franc</option>
                            <option value="GTQ">GTQ: Guatemalan Quetzal</option>
                            <option value="GYD">GYD: Guyanaese Dollar</option>
                            <option value="HKD">HKD: Hong Kong Dollar</option>
                            <option value="HNL">HNL: Honduran Lempira</option>
                            <option value="HRK">HRK: Croatian Kuna</option>
                            <option value="HTG">HTG: Haitian Gourde</option>
                            <option value="HUF">HUF: Hungarian Forint</option>
                            <option value="IDR">IDR: Indonesian Rupiah</option>
                            <option value="ILS">ILS: Israeli New Sheqel</option>
                            <option value="IMP">IMP: Manx pound</option>
                            <option value="INR">INR: Indian Rupee</option>
                            <option value="IQD">IQD: Iraqi Dinar</option>
                            <option value="IRR">IRR: Iranian Rial</option>
                            <option value="ISK">ISK: Icelandic Króna</option>
                            <option value="JEP">JEP: Jersey Pound</option>
                            <option value="JMD">JMD: Jamaican Dollar</option>
                            <option value="JOD">JOD: Jordanian Dinar</option>
                            <option value="JPY">JPY: Japanese Yen</option>
                            <option value="KES">KES: Kenyan Shilling</option>
                            <option value="KGS">KGS: Kyrgystani Som</option>
                            <option value="KHR">KHR: Cambodian Riel</option>
                            <option value="KMF">KMF: Comorian Franc</option>
                            <option value="KPW">KPW: North Korean Won</option>
                            <option value="KRW">KRW: South Korean Won</option>
                            <option value="KWD">KWD: Kuwaiti Dinar</option>
                            <option value="KYD">KYD: Cayman Islands Dollar</option>
                            <option value="KZT">KZT: Kazakhstani Tenge</option>
                            <option value="LAK">LAK: Laotian Kip</option>
                            <option value="LBP">LBP: Lebanese Pound</option>
                            <option value="LKR">LKR: Sri Lankan Rupee</option>
                            <option value="LRD">LRD: Liberian Dollar</option>
                            <option value="LSL">LSL: Lesotho Loti</option>
                            <option value="LYD">LYD: Libyan Dinar</option>
                            <option value="MAD">MAD: Moroccan Dirham</option>
                            <option value="MDL">MDL: Moldovan Leu</option>
                            <option value="MGA">MGA: Malagasy Ariary</option>
                            <option value="MKD">MKD: Macedonian Denar</option>
                            <option value="MMK">MMK: Myanma Kyat</option>
                            <option value="MNT">MNT: Mongolian Tugrik</option>
                            <option value="MOP">MOP: Macanese Pataca</option>
                            <option value="MRU">MRU: Mauritanian Ouguiya</option>
                            <option value="MUR">MUR: Mauritian Rupee</option>
                            <option value="MVR">MVR: Maldivian Rufiyaa</option>
                            <option value="MWK">MWK: Malawian Kwacha</option>
                            <option value="MXN">MXN: Mexican Peso</option>
                            <option value="MYR">MYR: Malaysian Ringgit</option>
                            <option value="MZN">MZN: Mozambican Metical</option>
                            <option value="NAD">NAD: Namibian Dollar</option>
                            <option value="NGN">NGN: Nigerian Naira</option>
                            <option value="NIO">NIO: Nicaraguan Córdoba</option>
                            <option value="NOK">NOK: Norwegian Krone</option>
                            <option value="NPR">NPR: Nepalese Rupee</option>
                            <option value="NZD">NZD: New Zealand Dollar</option>
                            <option value="OMR">OMR: Omani Rial</option>
                            <option value="PAB">PAB: Panamanian Balboa</option>
                            <option value="PEN">PEN: Peruvian Nuevo Sol</option>
                            <option value="PGK">PGK: Papua New Guinean Kina</option>
                            <option value="PHP">PHP: Philippine Peso</option>
                            <option value="PKR">PKR: Pakistani Rupee</option>
                            <option value="PLN">PLN: Polish Zloty</option>
                            <option value="PYG">PYG: Paraguayan Guarani</option>
                            <option value="QAR">QAR: Qatari Rial</option>
                            <option value="RON">RON: Romanian Leu</option>
                            <option value="RSD">RSD: Serbian Dinar</option>
                            <option value="RUB">RUB: Russian Ruble</option>
                            <option value="RWF">RWF: Rwandan Franc</option>
                            <option value="SAR">SAR: Saudi Riyal</option>
                            <option value="SBD">SBD: Solomon Islands Dollar</option>
                            <option value="SCR">SCR: Seychellois Rupee</option>
                            <option value="SDG">SDG: Sudanese Pound</option>
                            <option value="SEK">SEK: Swedish Krona</option>
                            <option value="SGD">SGD: Singapore Dollar</option>
                            <option value="SHP">SHP: Saint Helena Pound</option>
                            <option value="SLL">SLL: Sierra Leonean Leone</option>
                            <option value="SOS">SOS: Somali Shilling</option>
                            <option value="SRD">SRD: Surinamese Dollar</option>
                            <option value="SSP">SSP: South Sudanese Pound</option>
                            <option value="STD">STD: São Tomé and Príncipe Dobra (pre-2018)</option>
                            <option value="STN">STN: São Tomé and Príncipe Dobra</option>
                            <option value="SVC">SVC: Salvadoran Colón</option>
                            <option value="SYP">SYP: Syrian Pound</option>
                            <option value="SZL">SZL: Swazi Lilangeni</option>
                            <option value="THB">THB: Thai Baht</option>
                            <option value="TJS">TJS: Tajikistani Somoni</option>
                            <option value="TMT">TMT: Turkmenistani Manat</option>
                            <option value="TND">TND: Tunisian Dinar</option>
                            <option value="TOP">TOP: Tongan Pa anga</option>
                            <option value="TRY">TRY: Turkish Lira</option>
                            <option value="TTD">TTD: Trinidad and Tobago Dollar</option>
                            <option value="TWD">TWD: New Taiwan Dollar</option>
                            <option value="TZS">TZS: Tanzanian Shilling</option>
                            <option value="UAH">UAH: Ukrainian Hryvnia</option>
                            <option value="UGX">UGX: Ugandan Shilling</option>
                            <option value="USD">USD: United States Dollar</option>
                            <option value="UYU">UYU: Uruguayan Peso</option>
                            <option value="UZS">UZS: Uzbekistan Som</option>
                            <option value="VEF">VEF: Venezuelan Bolívar Fuerte (Old)</option>
                            <option value="VES">VES: Venezuelan Bolívar Soberano</option>
                            <option value="VND">VND: Vietnamese Dong</option>
                            <option value="VUV">VUV: Vanuatu Vatu</option>
                            <option value="WST">WST: Samoan Tala</option>
                            <option value="XAF">XAF: CFA Franc BEAC</option>
                            <option value="XAG">XAG: Silver Ounce</option>
                            <option value="XAU">XAU: Gold Ounce</option>
                            <option value="XCD">XCD: East Caribbean Dollar</option>
                            <option value="XDR">XDR: Special Drawing Rights</option>
                            <option value="XOF">XOF: CFA Franc BCEAO</option>
                            <option value="XPD">XPD: Palladium Ounce</option>
                            <option value="XPF">XPF: CFP Franc</option>
                            <option value="XPT">XPT: Platinum Ounce</option>
                            <option value="YER">YER: Yemeni Rial</option>
                            <option value="ZAR">ZAR: South African Rand</option>
                            <option value="ZMW">ZMW: Zambian Kwacha</option>
                            <option value="ZWL">ZWL: Zimbabwean Dollar</option>

                        </select>
                    </div>
                </div>


                <div class="flex justify-center items-center mt-8">
                    <button id="convertBtn" class="border  border-primary_button hover:bg-primary_button hover:text-white hover:font-semibold w-40 h-10 rounded-full duration-150 text-primary_button">Calculate</button>
                </div>
            </div>
        </div>

    </div>
    <div id="additionalDiv" class=" hidden mt-5 bg-primary_button text-white font-semibold !text-center py-3 lg:py-4 text-base xs:text-lg md:text-2xl rounded-lg">
        Result
    </div>

    <div class=" text-center mt-5 flex justify-center items-center">
        <div id="result"></div>
    </div>
</section>

<script src="./app/views/pages/currency-calculator/currency-calculator-script.js"></script>